export const FETCH_GROCERIES_LOADING = 'FETCH_GROCERIES_LOADING';
export const FETCH_GROCERIES_SUCCESS = 'FETCH_GROCERIES_SUCCESS';
export const FETCH_GROCERIES_FAILURE = 'FETCH_GROCERIES_FAILURE';
export const ADD_GROCERY_TO_CART = 'ADD_GROCERY_TO_CART';
export const REMOVE_GROCERY_FROM_CART = 'REMOVE_GROCERY_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
